# Generated by Django 5.1 on 2024-08-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=100)),
                ('telephon', models.CharField(max_length=15)),
                ('cours_suivant', models.CharField(max_length=100, null=True)),
                ('vacant', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
