# Generated by Django 5.1 on 2024-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='genre',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='registration_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
