# Generated by Django 5.1 on 2024-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0002_person_eleve_birthday_eleve_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='ville',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
